name: Deploy
on: [push]
jobs:
  Deploy-Mandelbrot-WebGPU:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
      - run: echo "Test"
      - name: Checkout
        uses: actions/checkout@v4
      - name: List
        run: |
          ls ${{ github.workspace }}
